using Microsoft.CodeAnalysis;
using System.Text;
using FastORM.Generator;

namespace FastORM.Generated;

internal static class SchemaEmitter
{
    public static string Emit(Compilation comp, SchemaModel model)
    {
        var sb = new StringBuilder();
        
        // Header
        sb.Append("// <auto-generated/>\n");
        sb.Append("#nullable enable\n\n");
        sb.Append("namespace FastORM.Generated\n{\n");
        sb.Append("    public static class ").Append(model.TableName).Append("_Schema_").Append(model.Line).Append("_").Append(model.Column).Append("\n    {\n");

        // Method Signature
        if (model.IsCreateTable)
        {
            var interceptAttr = comp.GetTypeByMetadataName("System.Runtime.CompilerServices.InterceptsLocationAttribute");
            bool supportsVersion = false;
            if (interceptAttr != null)
            {
                foreach (var ctor in interceptAttr.Constructors)
                {
                    if (ctor.Parameters.Length == 2 &&
                        ctor.Parameters[0].Type.SpecialType == SpecialType.System_Int32 &&
                        ctor.Parameters[1].Type.SpecialType == SpecialType.System_String)
                    { supportsVersion = true; break; }
                }
            }

            if (supportsVersion && model.InterceptVersion != 0 && model.InterceptData.Length > 0)
            {
                sb.Append("        [global::System.Runtime.CompilerServices.InterceptsLocation(version: ").Append(model.InterceptVersion).Append(", data: \"").Append(Escape(model.InterceptData)).Append("\")]\n");
            }
            else
            {
                sb.Append("#pragma warning disable CS9270\n");
                sb.Append("        [global::System.Runtime.CompilerServices.InterceptsLocation(@\"").Append(model.FilePath).Append("\", ").Append(model.Line).Append(", ").Append(model.Column).Append(")]\n");
                sb.Append("#pragma warning restore CS9270\n");
            }

            if (model.IsAsync)
                sb.Append("        public static async global::System.Threading.Tasks.Task CreateTableAsync(this global::FastORM.FastDbContext context, global::System.Threading.CancellationToken cancellationToken = default)\n        {\n");
            else
                sb.Append("        public static void CreateTable(this global::FastORM.FastDbContext context)\n        {\n");
                
            // Create Table Body
            sb.Append("            var sb = new System.Text.StringBuilder();\n");
            sb.Append("            if (context.Dialect == FastORM.SqlDialect.Sqlite) sb.Append(\"CREATE TABLE IF NOT EXISTS \").Append(context.Quote(\"").Append(model.TableName).Append("\")).Append(\" (\");\n");
            sb.Append("            else if (context.Dialect == FastORM.SqlDialect.MySql) sb.Append(\"CREATE TABLE IF NOT EXISTS \").Append(context.Quote(\"").Append(model.TableName).Append("\")).Append(\" (\");\n");
            sb.Append("            else if (context.Dialect == FastORM.SqlDialect.PostgreSql) sb.Append(\"CREATE TABLE IF NOT EXISTS \").Append(context.Quote(\"").Append(model.TableName).Append("\")).Append(\" (\");\n");
            sb.Append("            else sb.Append(\"CREATE TABLE \").Append(context.Quote(\"").Append(model.TableName).Append("\")).Append(\" (\");\n");
            
            var props = model.Columns;
            var pk = model.PrimaryKey;
            
            for (int i = 0; i < props.Count; i++)
            {
                var p = props[i];
                var isPk = pk != null && SymbolEqualityComparer.Default.Equals(p, pk);
                var type = p.Type;
                if (type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T && type is INamedTypeSymbol nts) type = nts.TypeArguments[0];
                var typeName = type.ToDisplayString();
                
                var def = model.ColumnDefinitions.TryGetValue(p.Name, out var d) ? d : new ColumnDefinition();

                if (i > 0) sb.Append("            sb.Append(\", \");\n");
                sb.Append("            sb.Append(context.Quote(\"").Append(ColumnName(p)).Append("\"));\n");
                
                sb.Append("            if (context.Dialect == FastORM.SqlDialect.Sqlite) {\n");
                if (!string.IsNullOrEmpty(def.CustomTypeName)) sb.Append("                sb.Append(\" ").Append(def.CustomTypeName).Append("\");\n");
                else if (typeName == "int" || typeName == "long" || typeName == "short" || typeName == "byte" || typeName == "bool") sb.Append("                sb.Append(\" INTEGER\");\n");
                else if (typeName == "float" || typeName == "double") sb.Append("                sb.Append(\" REAL\");\n");
                else if (typeName == "decimal") {
                    if (def.Precision.HasValue && def.Scale.HasValue) sb.Append("                sb.Append(\" DECIMAL(").Append(def.Precision).Append(",").Append(def.Scale).Append(")\");\n");
                    else sb.Append("                sb.Append(\" NUMERIC\");\n");
                }
                else if (typeName == "byte[]" || typeName == "System.Byte[]") sb.Append("                sb.Append(\" BLOB\");\n");
                else if (typeName == "string" || typeName == "System.Guid" || typeName == "System.DateTime" || typeName == "System.DateOnly" || typeName == "System.TimeOnly" || typeName == "System.DateTimeOffset") {
                    if (def.MaxLength.HasValue) sb.Append("                sb.Append(\" VARCHAR(").Append(def.MaxLength).Append(")\");\n");
                    else sb.Append("                sb.Append(\" TEXT\");\n");
                }
                else sb.Append("                sb.Append(\" TEXT\");\n");
                
                if (isPk) sb.Append("                sb.Append(\" PRIMARY KEY AUTOINCREMENT\");\n");
                else 
                {
                    if (def.IsRequired) sb.Append("                sb.Append(\" NOT NULL\");\n");
                    if (!string.IsNullOrEmpty(def.DefaultValueSql)) sb.Append("                sb.Append(\" DEFAULT \").Append(\"").Append(def.DefaultValueSql).Append("\");\n");
                }
                sb.Append("            }\n");
                sb.Append("            else if (context.Dialect == FastORM.SqlDialect.MySql) {\n");
                if (!string.IsNullOrEmpty(def.CustomTypeName)) sb.Append("                sb.Append(\" ").Append(def.CustomTypeName).Append("\");\n");
                else if (typeName == "int") sb.Append("                sb.Append(\" INT\");\n");
                else if (typeName == "long") sb.Append("                sb.Append(\" BIGINT\");\n");
                else if (typeName == "bool") sb.Append("                sb.Append(\" BIT\");\n");
                else if (typeName == "System.Guid") sb.Append("                sb.Append(\" CHAR(36)\");\n");
                else if (typeName == "byte[]" || typeName == "System.Byte[]") sb.Append("                sb.Append(\" LONGBLOB\");\n");
                else if (typeName == "string") {
                    if (def.MaxLength.HasValue) sb.Append("                sb.Append(\" VARCHAR(").Append(def.MaxLength).Append(")\");\n");
                    else sb.Append("                sb.Append(\" VARCHAR(255)\");\n");
                }
                else if (typeName == "System.DateTime" || typeName == "System.DateTimeOffset") sb.Append("                sb.Append(\" DATETIME\");\n");
                else if (typeName == "System.DateOnly") sb.Append("                sb.Append(\" DATE\");\n");
                else if (typeName == "System.TimeOnly") sb.Append("                sb.Append(\" TIME\");\n");
                else if (typeName == "float" || typeName == "double") sb.Append("                sb.Append(\" DOUBLE\");\n");
                else if (typeName == "decimal") {
                    if (def.Precision.HasValue && def.Scale.HasValue) sb.Append("                sb.Append(\" DECIMAL(").Append(def.Precision).Append(",").Append(def.Scale).Append(")\");\n");
                    else sb.Append("                sb.Append(\" DECIMAL(18,2)\");\n");
                }
                else sb.Append("                sb.Append(\" TEXT\");\n");
                
                if (isPk) sb.Append("                sb.Append(\" PRIMARY KEY AUTO_INCREMENT\");\n");
                else 
                {
                    if (def.IsRequired) sb.Append("                sb.Append(\" NOT NULL\");\n");
                    if (!string.IsNullOrEmpty(def.DefaultValueSql)) sb.Append("                sb.Append(\" DEFAULT \").Append(\"").Append(def.DefaultValueSql).Append("\");\n");
                }
                sb.Append("            }\n");
                sb.Append("            else if (context.Dialect == FastORM.SqlDialect.PostgreSql) {\n");
                if (isPk && (typeName == "int" || typeName == "long")) {
                    if (typeName == "int") sb.Append("                sb.Append(\" SERIAL PRIMARY KEY\");\n");
                    else sb.Append("                sb.Append(\" BIGSERIAL PRIMARY KEY\");\n");
                } else {
                    if (!string.IsNullOrEmpty(def.CustomTypeName)) sb.Append("                sb.Append(\" ").Append(def.CustomTypeName).Append("\");\n");
                    else if (typeName == "int") sb.Append("                sb.Append(\" INT\");\n");
                    else if (typeName == "long") sb.Append("                sb.Append(\" BIGINT\");\n");
                    else if (typeName == "bool") sb.Append("                sb.Append(\" BOOLEAN\");\n");
                    else if (typeName == "System.Guid") sb.Append("                sb.Append(\" UUID\");\n");
                    else if (typeName == "byte[]" || typeName == "System.Byte[]") sb.Append("                sb.Append(\" BYTEA\");\n");
                    else if (typeName == "System.DateTime") sb.Append("                sb.Append(\" TIMESTAMP\");\n");
                    else if (typeName == "System.DateTimeOffset") sb.Append("                sb.Append(\" TIMESTAMPTZ\");\n");
                    else if (typeName == "System.DateOnly") sb.Append("                sb.Append(\" DATE\");\n");
                    else if (typeName == "System.TimeOnly") sb.Append("                sb.Append(\" TIME\");\n");
                    else if (typeName == "float" || typeName == "double") sb.Append("                sb.Append(\" DOUBLE PRECISION\");\n");
                    else if (typeName == "decimal") {
                        if (def.Precision.HasValue && def.Scale.HasValue) sb.Append("                sb.Append(\" DECIMAL(").Append(def.Precision).Append(",").Append(def.Scale).Append(")\");\n");
                        else sb.Append("                sb.Append(\" DECIMAL(18,2)\");\n");
                    }
                    else if (typeName == "string") {
                        if (def.MaxLength.HasValue) sb.Append("                sb.Append(\" VARCHAR(").Append(def.MaxLength).Append(")\");\n");
                        else sb.Append("                sb.Append(\" TEXT\");\n");
                    }
                    else sb.Append("                sb.Append(\" TEXT\");\n");

                    if (def.IsRequired) sb.Append("                sb.Append(\" NOT NULL\");\n");
                    if (!string.IsNullOrEmpty(def.DefaultValueSql)) sb.Append("                sb.Append(\" DEFAULT \").Append(\"").Append(def.DefaultValueSql).Append("\");\n");
                }
                sb.Append("            }\n");
                sb.Append("            else {\n");
                if (!string.IsNullOrEmpty(def.CustomTypeName)) sb.Append("                sb.Append(\" ").Append(def.CustomTypeName).Append("\");\n");
                else if (typeName == "int") sb.Append("                sb.Append(\" INT\");\n");
                else if (typeName == "long") sb.Append("                sb.Append(\" BIGINT\");\n");
                else if (typeName == "bool") sb.Append("                sb.Append(\" BIT\");\n");
                else if (typeName == "System.Guid") sb.Append("                sb.Append(\" UNIQUEIDENTIFIER\");\n");
                else if (typeName == "byte[]" || typeName == "System.Byte[]") sb.Append("                sb.Append(\" VARBINARY(MAX)\");\n");
                else if (typeName == "string") {
                    if (def.MaxLength.HasValue) sb.Append("                sb.Append(\" NVARCHAR(").Append(def.MaxLength).Append(")\");\n");
                    else sb.Append("                sb.Append(\" NVARCHAR(255)\");\n");
                }
                else if (typeName == "System.DateTime") sb.Append("                sb.Append(\" DATETIME2\");\n");
                else if (typeName == "System.DateTimeOffset") sb.Append("                sb.Append(\" DATETIMEOFFSET\");\n");
                else if (typeName == "System.DateOnly") sb.Append("                sb.Append(\" DATE\");\n");
                else if (typeName == "System.TimeOnly") sb.Append("                sb.Append(\" TIME\");\n");
                else if (typeName == "float" || typeName == "double") sb.Append("                sb.Append(\" FLOAT\");\n");
                else if (typeName == "decimal") {
                    if (def.Precision.HasValue && def.Scale.HasValue) sb.Append("                sb.Append(\" DECIMAL(").Append(def.Precision).Append(",").Append(def.Scale).Append(")\");\n");
                    else sb.Append("                sb.Append(\" DECIMAL(18,2)\");\n");
                }
                else sb.Append("                sb.Append(\" NVARCHAR(MAX)\");\n");
                
                if (isPk) sb.Append("                sb.Append(\" IDENTITY PRIMARY KEY\");\n");
                else 
                {
                    if (def.IsRequired) sb.Append("                sb.Append(\" NOT NULL\");\n");
                    if (!string.IsNullOrEmpty(def.DefaultValueSql)) sb.Append("                sb.Append(\" DEFAULT \").Append(\"").Append(def.DefaultValueSql).Append("\");\n");
                }
                sb.Append("            }\n");
            }
            sb.Append("            sb.Append(\")\");\n");

            // Indexes
            foreach (var idx in model.Indexes)
            {
                var idxName = idx.Name;
                var colNames = new List<string>();
                foreach(var c in idx.Columns) {
                     var p = model.Columns.FirstOrDefault(prop => prop.Name == c);
                     if(p != null) colNames.Add(ColumnName(p));
                }
                if(colNames.Count == 0) continue;

                if (string.IsNullOrEmpty(idxName))
                {
                    idxName = $"IX_{model.TableName}_{string.Join("_", colNames)}";
                }

                var unique = idx.IsUnique ? "UNIQUE " : "";

                sb.Append("            sb.Append(\"; CREATE ").Append(unique).Append("INDEX \").Append(context.Quote(\"").Append(idxName).Append("\")).Append(\" ON \").Append(context.Quote(\"").Append(model.TableName).Append("\")).Append(\" (\");\n");
                for(int k=0; k<colNames.Count; k++) {
                     if(k>0) sb.Append("            sb.Append(\", \");\n");
                     sb.Append("            sb.Append(context.Quote(\"").Append(colNames[k]).Append("\"));\n");
                }
                sb.Append("            sb.Append(\")\");\n");
            }
        
            sb.Append("            var conn = context.Connection;\n");
            if (model.IsAsync) sb.Append("            if (conn.State != System.Data.ConnectionState.Open) await conn.OpenAsync(cancellationToken);\n");
            else sb.Append("            if (conn.State != System.Data.ConnectionState.Open) conn.Open();\n");
            sb.Append("            using var cmd = context.CreateCommand();\n");
            sb.Append("            cmd.CommandText = sb.ToString();\n");
            if (model.IsAsync) sb.Append("            await cmd.ExecuteNonQueryAsync(cancellationToken);\n");
            else sb.Append("            cmd.ExecuteNonQuery();\n");
            sb.Append("        }\n");
        }
        else if (model.IsDropTable)
        {
            var interceptAttr = comp.GetTypeByMetadataName("System.Runtime.CompilerServices.InterceptsLocationAttribute");
            bool supportsVersion = false;
            if (interceptAttr != null)
            {
                foreach (var ctor in interceptAttr.Constructors)
                {
                    if (ctor.Parameters.Length == 2 &&
                        ctor.Parameters[0].Type.SpecialType == SpecialType.System_Int32 &&
                        ctor.Parameters[1].Type.SpecialType == SpecialType.System_String)
                    { supportsVersion = true; break; }
                }
            }

            if (supportsVersion && model.InterceptVersion != 0 && model.InterceptData.Length > 0)
            {
                sb.Append("        [global::System.Runtime.CompilerServices.InterceptsLocation(version: ").Append(model.InterceptVersion).Append(", data: \"").Append(Escape(model.InterceptData)).Append("\")]\n");
            }
            else
            {
                sb.Append("#pragma warning disable CS9270\n");
                sb.Append("        [global::System.Runtime.CompilerServices.InterceptsLocation(@\"").Append(model.FilePath).Append("\", ").Append(model.Line).Append(", ").Append(model.Column).Append(")]\n");
                sb.Append("#pragma warning restore CS9270\n");
            }

            if (model.IsAsync)
                sb.Append("        public static async global::System.Threading.Tasks.Task DropTableAsync(this global::FastORM.FastDbContext context, global::System.Threading.CancellationToken cancellationToken = default)\n        {\n");
            else
                sb.Append("        public static void DropTable(this global::FastORM.FastDbContext context)\n        {\n");

            sb.Append("            var sb = new System.Text.StringBuilder();\n");
            sb.Append("            if (context.Dialect == FastORM.SqlDialect.Sqlite) sb.Append(\"DROP TABLE IF EXISTS \").Append(context.Quote(\"").Append(model.TableName).Append("\"));\n");
            sb.Append("            else if (context.Dialect == FastORM.SqlDialect.MySql) sb.Append(\"DROP TABLE IF EXISTS \").Append(context.Quote(\"").Append(model.TableName).Append("\"));\n");
            sb.Append("            else if (context.Dialect == FastORM.SqlDialect.PostgreSql) sb.Append(\"DROP TABLE IF EXISTS \").Append(context.Quote(\"").Append(model.TableName).Append("\"));\n");
            sb.Append("            else sb.Append(\"DROP TABLE \").Append(context.Quote(\"").Append(model.TableName).Append("\"));\n");
        
            sb.Append("            var conn = context.Connection;\n");
            if (model.IsAsync) sb.Append("            if (conn.State != System.Data.ConnectionState.Open) await conn.OpenAsync(cancellationToken);\n");
            else sb.Append("            if (conn.State != System.Data.ConnectionState.Open) conn.Open();\n");
            sb.Append("            using var cmd = context.CreateCommand();\n");
            sb.Append("            cmd.CommandText = sb.ToString();\n");
            if (model.IsAsync) sb.Append("            await cmd.ExecuteNonQueryAsync(cancellationToken);\n");
            else sb.Append("            cmd.ExecuteNonQuery();\n");
            sb.Append("        }\n");
        }
        
        sb.Append("    }\n");
        sb.Append("}\n");
        
        return sb.ToString();
    }
    
    static string ColumnName(IPropertySymbol p)
    {
        foreach (var a in p.GetAttributes())
        {
            if (a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DataAnnotations.Schema.ColumnAttribute")
            {
                foreach (var na in a.NamedArguments)
                {
                    if (na.Key == "Name")
                    {
                        var v = na.Value.Value as string;
                        if (v != null) return v;
                    }
                }
                if (a.ConstructorArguments.Length > 0)
                {
                    var v = a.ConstructorArguments[0].Value as string;
                    if (v != null) return v;
                }
            }
        }
        return p.Name;
    }

    static string Escape(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
